version: '3'
services:
    webapi1:
        image: shwang1a/webapi1
        container_name: webapi1

    console:
        depends_on:
          - webapi1
        image: shwang1a/client-image
        container_name: client-image
        environment:
          WebApi1Url: "http://webapi1"
